#!/usr/bin/env python3
"""Generates the static site. Run: python3 build.py"""
import os, html

OUT = os.path.dirname(os.path.abspath(__file__))

NAME = "Tyler Oberquell"
ROLE = "Comp Sci Student"
NOTE = ""
GH = "https://github.com/The-T-Time"
ITCH = "https://the-ttime.itch.io"
LI = "https://www.linkedin.com/in/tyler-oberquell"

I_GH = '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>'
I_PAD = '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 5h12a5 5 0 015 5v4a5 5 0 01-5 5h-.6a3 3 0 01-2.4-1.2L14 16.5h-4l-1 1.3A3 3 0 016.6 19H6a5 5 0 01-5-5v-4a5 5 0 015-5zm1.2 3.4v1.8H5.4v1.8h1.8v1.8H9v-1.8h1.8v-1.8H9V8.4H7.2zm9.3.6a1.4 1.4 0 100 2.8 1.4 1.4 0 000-2.8zm-2.6 2.8a1.4 1.4 0 100 2.8 1.4 1.4 0 000-2.8z"/></svg>'
I_LI = '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.225 0z"/></svg>'

FONTS = ('<link rel="preconnect" href="https://fonts.googleapis.com">\n'
         '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
         '<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400..800'
         '&family=Inter:wght@400..700&display=swap" rel="stylesheet">')


def head(title, desc, root):
    return f"""<!DOCTYPE html>
<!-- GENERATED by build.py — edits here are overwritten when you re-run it.
     Change content in build.py, or delete build.py and edit these files directly. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#0f1115">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:type" content="website">
{FONTS}
<link rel="stylesheet" href="{root}assets/css/style.css">
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
"""


def nav(active, root):
    def li(label, href, key):
        cur = ' aria-current="page"' if key == active else ''
        return f'<li><a href="{href}"{cur}>{label}</a></li>'
    return f"""<header class="nav">
  <div class="shell nav__inner">
    <a class="nav__brand" href="{root}index.html">{NAME}</a>
    <nav aria-label="Primary">
      <ul class="nav__links">
        {li('Home', root + 'index.html', 'home')}
        {li('Projects', root + 'projects.html', 'projects')}
      </ul>
    </nav>
  </div>
</header>
"""


def footer(root):
    return f"""<footer class="footer">
  <div class="shell footer__inner">
    <span>Built and maintained by {NAME}. No trackers, no cookies.</span>
    <span><a href="{GH}">GitHub</a> &nbsp;·&nbsp; <a href="{ITCH}">itch.io</a> &nbsp;·&nbsp; <a href="{LI}">LinkedIn</a></span>
  </div>
</footer>

</body>
</html>
"""


def tags(items, plain=False):
    cls = "tags tags--plain" if plain else "tags"
    return f'<ul class="{cls}">' + "".join(f"<li>{t}</li>" for t in items) + "</ul>"


def buttons(project, root, primary_label="View Project"):
    out = []
    if project.get("page"):
        out.append(f'<a class="btn btn--primary" href="{root}projects/{project["page"]}">{primary_label}</a>')
    if project.get("github"):
        out.append(f'<a class="btn btn--ghost" href="{project["github"]}">{I_GH}GitHub</a>')
    if project.get("itch"):
        out.append(f'<a class="btn btn--ghost" href="{project["itch"]}">{I_PAD}Play on itch.io</a>')
    return '<div class="actions">' + "".join(out) + "</div>"


# ---------------------------------------------------------------- project data
P = {}

P["pi-server"] = dict(
    slug="pi-server", page="pi-server.html", title="Pi Server",
    img="pi-server.svg",
    short="A self-hosted control panel for my home network, running on a Raspberry Pi 5. Live hardware stats, network scanning, remote power control and push alerts — all on one page.",
    long="I wanted one page that could tell me whether anything at home was broken. It became a full monitoring and control stack running as a system service on a Raspberry Pi 5.",
    tools=["Python", "FastAPI", "WebSockets", "SQLite", "Linux", "systemd"],
    github=None, itch=None,
    info=[("Type", "Self-hosted web app"), ("Backend", "Python, FastAPI"),
          ("Frontend", "HTML, CSS, JS"), ("Storage", "SQLite"),
          ("Host", "Raspberry Pi 5"), ("Status", "Running daily"), ("Source", "Private")],
    desc_meta="A self-hosted monitoring and control dashboard for a Raspberry Pi 5 home server: FastAPI, WebSockets, SQLite, network scanning, remote power control and push alerts.",
    does="""<p>A single-page control panel for my home network. It shows live hardware stats for the Pi and my desktop, an inventory of everything connected, the status of the services I self-host, and controls for the things I'd otherwise have to walk across the house to do.</p>
        <p>The brief I gave myself was narrow: everything I want to know should be visible without clicking, and everything I want to do should be one button. Every feature since has had to earn its place against that.</p>""",
    features=[
        ("Live system stats", "CPU, memory, temperature, disk and uptime for the Pi, streamed over a WebSocket rather than polled, so the numbers move in real time instead of stepping."),
        ("Desktop monitoring", "A companion agent on my Windows PC reports CPU, memory, disk and GPU telemetry back to the dashboard, with GPU stats read from NVIDIA's management library directly."),
        ("Remote power control", "Wake-on-LAN to start the PC, plus a queued command channel for sleep and shutdown, so a control issued while the PC is off isn't lost."),
        ("Network scanning", "Regular scans discover what's connected. Results are stored with history, and devices can be searched, sorted, tagged, renamed, annotated or marked reviewed."),
        ("Ad blocking", "Integrates with the Pi-hole API rather than reimplementing it, surfacing query and blocking stats alongside everything else."),
        ("Connectivity", "Latency polling, on-demand speed tests, and a VPN status panel with a restart control for when the mesh network gets stuck."),
        ("Push alerts", "Threshold and service-health alerts delivered to my phone, so I find out something's wrong without having the dashboard open."),
    ],
    how="""<h3>Backend</h3>
        <p>Python and FastAPI. Stats that change constantly go out over WebSockets; everything else is a plain REST endpoint. Device history and scan results live in SQLite. Network discovery shells out to <code>nmap</code> and parses the results. External integrations — the ad blocker's REST API, the VPN's status output, the push notification service — are each wrapped behind a small module, so a change on their side touches one file.</p>
        <h3>Frontend</h3>
        <p>Hand-written HTML, CSS and JavaScript, no framework. The layout is a four-region shell: a permanent left navigation sidebar moving from the overview down through each subsystem, a top bar with labelled status dots for at-a-glance health, a card grid as the main content area, and a right sidebar on the overview holding a merged Pi-and-PC stats card. Adding a page means adding a nav entry and a content module, nothing else.</p>
        <h3>Config that survives its own updates</h3>
        <p>Early on, updating the dashboard meant replacing the application directory — which also wiped the credentials and settings stored inside it. Now every piece of persistent state lives in a separate config directory outside the application tree. Updating is a directory swap with nothing to back up first.</p>
        <h3>Commands for a machine that isn't listening</h3>
        <p>Sleep and shutdown can't be pushed to a PC that's asleep, and Wake-on-LAN is fire-and-forget with no acknowledgement. Rather than making the dashboard talk to the PC synchronously, controls write to a command queue that the agent drains on its own schedule. The dashboard records intent; delivery is the agent's problem.</p>
        <h3>Deployment</h3>
        <p>The dashboard runs as a <code>systemd</code> service, so it starts on boot and restarts itself if it crashes. The PC agent starts automatically through Windows Task Scheduler under a dedicated local account. A direct Ethernet link between the Pi and the desktop gives Wake-on-LAN a reliable path that doesn't depend on Wi-Fi.</p>""",
    gallery=["Overview with live stats", "Device inventory", "Network and connectivity"],
)

P["diamondsim"] = dict(
    slug="diamondsim", page="diamondsim.html", title="DiamondSim",
    img="diamondsim.svg",
    short="A desktop app that plays out the rest of an MLB season thousands of times and reports each team's playoff odds, with ratings adjusted per game for pitching, lineup and bullpen fatigue.",
    long="Play the rest of the baseball season a few thousand times, count how often each team makes the playoffs, and show the answer as a percentage you can argue with.",
    tools=["Python", "CustomTkinter", "Monte Carlo", "Concurrency", "Caching"],
    github="https://github.com/USERNAME/diamondsim", itch=None,
    info=[("Type", "Desktop app"), ("Language", "Python"), ("UI", "CustomTkinter"),
          ("Method", "Monte Carlo"), ("Status", "In development")],
    desc_meta="A Python desktop app that simulates the rest of an MLB season thousands of times to produce playoff odds, with per-game rating adjustments and a threaded simulation engine.",
    does="""<p>DiamondSim takes the current state of an MLB season and simulates every remaining game, thousands of times over. Each simulated season produces a final set of standings and a postseason bracket; run enough of them and the frequency of each outcome becomes a probability.</p>
        <p>The app reports playoff odds, division odds and championship odds, alongside the standings each run produced. Simulations run off the main thread, so the interface stays usable while thousands of seasons play out.</p>""",
    features=[
        ("Elo ratings from real results only", "Team ratings move on completed games and nothing else. The moment simulated outcomes feed back into ratings, a team that gets lucky once starts the next run stronger and the whole distribution drifts away from reality."),
        ("Per-game effective ratings", "What decides a simulated game is a rating computed fresh for that matchup from the team rating plus adjustments for the announced starter, the lineup and the bullpen. It's used once and thrown away."),
        ("Bullpen fatigue", "Usage accumulates across a simulated season, so a team that burns its relievers through a stretch of close games is measurably weaker a week later."),
        ("Round-by-round postseason", "The bracket is simulated series by series from the standings each run produces, rather than approximated with a formula."),
        ("Threaded engine", "Thousands of seasons run in the background with a responsive interface and shared caching in front of the data layer."),
    ],
    how="""<h3>Two brackets that are the same bracket</h3>
        <p>Aggregating results means recognising when two simulated postseasons produced the same outcome. Getting that comparison wrong quietly splits identical results into separate buckets, and every reported probability comes out too low.</p>
        <p>Two mistakes caused that. Home-field assignment was part of the comparison key even though it isn't a visible outcome, so the same set of series winners looked like two brackets depending on venue. And the two division series happen in parallel with no meaningful ordering, so the same pair of results compared unequal purely because of storage order. The key now excludes home field and stores the parallel series as an unordered pair, which is what they actually are.</p>
        <h3>Impossible odds as a bug report</h3>
        <p>At one point six teams showed 100% playoff odds, which is arithmetically impossible — there aren't that many spots. Rather than clamping the display, I traced it back through the aggregation to the underlying cause. Outputs that violate the rules of the domain are the most useful bugs you get, because they're unambiguous.</p>
        <h3>Threads racing over the same cache</h3>
        <p>Concurrent writes were corrupting shared cache files in a way that was masked for a long time by a per-team file layout — collisions were rare and looked like bad data rather than a race. The fix was per-store locks plus writing to temporary files named with the process ID, thread ID and a unique identifier before moving them into place, so two writers can never be mid-write on the same path.</p>
        <h3>A layout that only broke for one division</h3>
        <p>One division's standings table was cutting off text while every other division rendered fine. The cause was column widths estimated by counting characters and guessing a per-character width — an assumption that holds until one team's name is wide enough to break it. Replacing the guess with real text measurement from the font itself fixed it permanently.</p>
        <h3>Structure</h3>
        <p>Simulation logic and interface code never mix; they're kept apart by a dedicated runner that owns the boundary, which is what makes the engine testable without a window on screen. State objects are immutable and updated by producing modified copies, so a half-applied update can't leave a season inconsistent. Every bug that gets fixed gets a regression test alongside it.</p>""",
    gallery=["Playoff odds by team", "Division standings", "Postseason bracket outcomes"],
)

P["raincheck"] = dict(
    slug="raincheck", page="raincheck.html", title="RainCheck",
    img="raincheck.svg",
    short="A native Android weather app that queries several forecast providers at once, rejects the outliers statistically and shows you the consensus.",
    long="Every weather app tells you what one provider thinks. RainCheck asks several, notices when one of them is wrong, and tells you what the rest agree on.",
    tools=["Kotlin", "Android", "Retrofit", "WorkManager", "AlarmManager"],
    github="https://github.com/USERNAME/raincheck", itch=None,
    info=[("Type", "Android app"), ("Language", "Kotlin"), ("UI", "Android Views"),
          ("Networking", "Retrofit"), ("Status", "Version 1.0"), ("License", "MIT")],
    desc_meta="A native Android weather app in Kotlin that aggregates several forecast providers, rejects outliers statistically, and runs three independent notification systems.",
    does="""<p>A native Android weather app built on the classic View system rather than Compose. Current conditions, hourly and daily forecasts, severe weather alerts, and a notification system I actually leave switched on.</p>
        <p>What makes it different is underneath. Forecast providers disagree, sometimes badly, and picking one means inheriting whatever that provider gets wrong in your area. RainCheck queries several and combines them, which turns a data-source problem into a statistics problem.</p>""",
    features=[
        ("Multi-source forecasts", "Several providers are queried in parallel and reconciled into one number, so a single bad source can't skew what you see."),
        ("Three independent notification systems", "A daily summary on an exact alarm, precipitation warnings on background work scheduling, and severe weather alerts from the national service. They're genuinely separate because their timing requirements are."),
        ("Shared notification plumbing", "All three build content through one builder and check one event tracker for deduplication, so you don't get told about the same storm twice."),
        ("Precipitation classified properly", "Rain, drizzle, thunderstorms, snow, and freezing rain or sleet are distinguished, each with its own notification wording. \u201cPrecipitation expected\u201d isn't useful when the answer is black ice."),
        ("A real permission model", "Location permission is treated as three states — always, while in use, and denied — rather than the usual granted/not-granted binary, because background notifications need something foreground display doesn't."),
        ("Considered motion", "Theme switching animates, and screen transitions are set at theme level so navigation feels consistent everywhere."),
    ],
    how="""<h3>Combining sources that disagree</h3>
        <p>Averaging several forecasts sounds like a one-liner, and it isn't. A plain mean is exactly as vulnerable to one bad source as using that source alone — a provider reporting a temperature twenty degrees off drags the average with it, and the user has no way to know.</p>
        <p>So before anything is averaged, outliers are rejected using a modified Z-score based on median absolute deviation. That's a robust measure: unlike standard deviation, it isn't itself distorted by the outlier it's meant to catch. Values too far from the median get dropped, and only the survivors are averaged. The result degrades gracefully — a provider going down or going haywire doesn't show a wrong number, it just widens the spread of what's left.</p>
        <h3>Disabled controls that explain themselves</h3>
        <p>If you haven't granted background location, the controls depending on it should look unavailable — but a fully disabled control can't tell you <em>why</em>, which leaves users stuck. The fix was separating the two concerns that \u201cdisabled\u201d normally bundles: transparency handles the visual dimming so the control reads as inactive, while the touch handler stays live and shows an explanation with a route to fixing it.</p>
        <h3>An expand animation without the flash</h3>
        <p>Expanding a forecast row with Android's default automatic transition produced a visible flash, because the default runs its fade and its bounds change in sequence, briefly showing content at the wrong size. Composing the transition by hand, with bounds and fade running in parallel, removed it. Nobody notices this fix, which is the point.</p>
        <h3>A master switch that doesn't destroy your settings</h3>
        <p>Turning notifications off globally and back on used to reset every sub-setting to its default, silently undoing configuration the user had done deliberately. The master toggle now gates delivery without writing to the individual settings at all.</p>
        <h3>Published properly</h3>
        <p>The repository ships with a README, an architecture document, an API reference, a changelog and an MIT license. All traffic is HTTPS; the cleartext exemption was removed rather than left in \u201cjust in case\u201d. Before release I removed dead utility classes, unused endpoints, stale manifest entries, orphaned strings and around 130 unused drawable icons, and renamed internals that had drifted from what they meant. A codebase that lies about itself is one you can't trust six months later.</p>""",
    gallery=["Current conditions", "Expanded forecast", "Notification settings"],
)

P["snake"] = dict(
    slug="snake", page="snake-gone-rogue.html", title="Snake Gone Rogue",
    img="snake-gone-rogue.svg",
    short="Snake, rebuilt as a roguelite. Shop upgrades, run modifiers, a rising quota, and an endless mode where the board wraps in both directions.",
    long="Snake is a solved problem. So I broke it: added a shop, permanent upgrades, run modifiers and a debt you have to pay off, then spent most of my time on the rendering.",
    tools=["Python", "pygame", "Game design", "Rendering", "Save systems"],
    github=None, itch="https://USERNAME.itch.io/snake-gone-rogue",
    info=[("Type", "Desktop game"), ("Language", "Python"), ("Framework", "pygame"),
          ("Version", "0.7.x"), ("Art", "Hand-drawn, 16×16"), ("Status", "In development")],
    desc_meta="A roguelite built on Snake in Python and pygame: shop upgrades, run modifiers, a quota system, and a wrapping endless mode that took two rendering rewrites.",
    does="""<p>A roguelite where the run loop is Snake. You eat apples to earn currency, spend it in a shop between rounds, and try to hit a quota that climbs every round. Miss it and the run ends — the debt system means playing it safe eventually loses too, so you're pushed into taking risks you don't want to take.</p>
        <p>Upgrades come in two flavours. Temporary ones last the current run and stack in ways I deliberately didn't balance too carefully, because the broken combinations are the fun part. Permanent ones are bought with a separate currency and persist across every future run through a slot-based save system, so the game opens up the longer you play it.</p>""",
    features=[
        ("A shop with real decisions", "Scrollable temporary upgrades, a randomised set of permanent slots with per-slot purchase locks, a reroll, and a modifier reveal that shows what you're signing up for before you commit."),
        ("Run modifiers", "Conditions rolled at the start of a run that change the rules — board size, speed, apple behaviour — and shift the risk calculation for everything you buy."),
        ("Multiple apple types", "Standard, rotten, silver and frost, each with different effects on score, length and speed."),
        ("Endless mode", "The board wraps on both axes, so the play space is topologically a torus. This turned out to be the hardest part of the whole project."),
        ("Checkpoints and pausing", "Between-run continuity, so a long session doesn't have to be one sitting."),
        ("Persistent saves", "Multiple slots, each holding permanent upgrades, currency and progression state."),
        ("Custom assets", "Hand-drawn 16×16 sprites for every snake orientation and apple variant, a seamless pattern texture for the body, a pixel font, and sound effects through a central manager."),
    ],
    how="""<h3>Structure</h3>
        <p>The codebase splits into four packages that each own one concern: <code>game/</code> for rules and state, <code>screen/</code> for everything drawable, <code>system/</code> for shared services, and <code>data/</code> for saves and definitions. Screens are self-contained modules rather than branches in one giant loop, which is what made it possible to add a shop, a pause screen and a checkpoint flow without the main loop turning into a maze.</p>
        <p>Sprites, sounds and fonts load once at startup through dedicated managers, so nothing touches the disk mid-frame. The pixel font is wrapped in a class that handles automatic uppercasing and blends in fallback glyphs for missing characters, which saved me drawing an entire character set by hand.</p>
        <h3>Rendering a wrapping snake without flicker</h3>
        <p>In endless mode a snake crossing the right edge has to appear on the left at the same time. My first approach decided, for each point in the body, which copy of the board it was nearest to. That works right up until two adjacent points disagree, at which point a segment stretches across the entire screen for one frame and the whole thing strobes.</p>
        <p>The fix was to stop thinking per point. The final renderer draws the <em>entire</em> body as rigid complete copies, each offset by a whole board width or height. Every copy is internally consistent because it's the same geometry translated; the ones off screen are simply never seen. Flicker gone, and the code got shorter.</p>
        <h3>Apples that move across a wrapping board</h3>
        <p>Moving apples needed two separate fixes I initially thought were one bug. The first was logical: their position had to loop at the wrap boundary rather than run off the edge. The second was visual: an apple near a corner can legitimately need to appear in more than one place at once, which meant checking a three-by-three neighbourhood of board tiles and drawing a copy wherever it landed on screen.</p>
        <h3>Input that doesn't eat your turns</h3>
        <p>At speed, players queue two direction changes faster than one game tick. Handling input directly meant the second press overwrote the first and the snake missed the turn — or worse, accepted a reversal into its own neck. Direction changes now go into a queue drained one per tick, with each entry validated against the direction actually in effect when it's consumed rather than when it was pressed.</p>
        <h3>A body that overlaps itself while interpolating</h3>
        <p>Movement is interpolated per frame, so segments occupy fractional positions between cells, and during a turn the drawn quads for two neighbouring segments can overlap and produce a visible seam. Getting this right took rewriting the ribbon renderer twice; the final version draws the body as a continuous textured strip rather than a sequence of independent sprites.</p>
        <h3>What's next</h3>
        <p>The engine and systems are in good shape; what holds the version number back is content breadth. More modifiers, upgrades and apple types, plus another balance pass on shop pricing. Background music is the other open item — it needs its own scheduler instance so stopping the music doesn't also kill sound effects.</p>""",
    gallery=["Gameplay — standard mode", "The shop between rounds", "Endless mode at the wrap boundary"],
)

P["benchmark"] = dict(
    slug="benchmark", page=None, title="Human Benchmark Bot",
    img="benchmark-bot.svg",
    short="A browser automation tool that plays the Human Benchmark reaction and typing tests, driven from a small desktop control panel.",
    tools=["Python", "Selenium", "Tkinter", "Threading"],
    github="https://github.com/USERNAME/human-benchmark-bot", itch=None,
)

P["calculator"] = dict(
    slug="calculator", page=None, title="Scientific Calculator",
    img="calculator.svg",
    short="A desktop calculator running on Python's decimal module instead of floats, with a live settings page for angle mode, precision and notation, plus a unit converter across eight categories.",
    tools=["Python", "CustomTkinter", "decimal", "JSON config"],
    github="https://github.com/USERNAME/calculator", itch=None,
)

FEATURED = ["diamondsim", "raincheck", "snake"]
ALL = ["pi-server", "diamondsim", "raincheck", "snake", "benchmark", "calculator"]


def card(key, root, compact=False):
    p = P[key]
    media_target = f'{root}projects/{p["page"]}' if p.get("page") else (p.get("github") or p.get("itch") or "#")
    title_html = f'<a href="{root}projects/{p["page"]}">{p["title"]}</a>' if p.get("page") else p["title"]
    cls = "card card--compact" if compact else "card"
    tool_list = p["tools"][:3] if compact else p["tools"]
    return f"""        <article class="{cls}">
          <a class="card__media" href="{media_target}" tabindex="-1" aria-hidden="true"><img src="{root}assets/img/{p['img']}" alt=""></a>
          <div class="card__body">
            <h3 class="card__title">{title_html}</h3>
            <p class="card__desc">{p['short']}</p>
            {tags(tool_list, plain=True)}
            {buttons(p, root)}
          </div>
        </article>"""


# ---------------------------------------------------------------- home
def build_home():
    cards = "\n".join(card(k, "", compact=True) for k in FEATURED)
    html_out = head(f"{NAME} — Projects", "Personal software projects: a roguelite game engine, an MLB season simulator, a multi-source Android weather app and a self-hosted home server dashboard.", "")
    html_out += nav("home", "")
    html_out += f"""
<main id="main" class="page page--fit">
  <div class="shell layout">

    <aside class="sidebar">
      <h1 class="sidebar__name">{NAME}</h1>
      <p class="sidebar__role">{ROLE}</p>
      <p class="sidebar__note">{NOTE}</p>
      <nav class="sidebar__links" aria-label="Elsewhere">
        <a href="{GH}">{I_GH}<span>GitHub</span></a>
        <a href="{ITCH}">{I_PAD}<span>itch.io</span></a>
        <a href="{LI}">{I_LI}<span>LinkedIn</span></a>
      </nav>
    </aside>

    <div class="main-col">

      <section class="half half--top">
        <div class="panel panel--tight duo">
          <div class="duo__about">
            <h2 class="minihead">About Me</h2>
            <p>Self-taught programmer who builds games, desktop tools and home-server software for the pleasure of solving the problem in front of me. I care about architecture that holds up months later and root-cause fixes over workarounds.</p>
          </div>
          <div class="duo__skills">
            <h2 class="minihead">Skills</h2>
            {tags(["Python", "Kotlin", "JavaScript", "pygame", "FastAPI", "Android SDK", "CustomTkinter", "SQLite", "Linux", "Git"], plain=True)}
          </div>
        </div>
      </section>

      <section class="half half--bottom">
        <div class="section__head">
          <h2 class="section__title">Featured Projects</h2>
          <a class="section__link" href="projects.html">See all projects</a>
        </div>
        <div class="cardrow-3">
{cards}
        </div>
      </section>

    </div>
  </div>
</main>

"""
    html_out += footer("")
    open(os.path.join(OUT, "index.html"), "w").write(html_out)


# ---------------------------------------------------------------- projects
def build_projects():
    cards = "\n".join(card(k, "") for k in ALL)
    html_out = head(f"Projects — {NAME}", "Every project worth showing: a roguelite game, a season simulator, an Android weather app, a home server dashboard and a couple of smaller tools.", "")
    html_out += nav("projects", "")
    html_out += f"""
<main id="main" class="page">
  <div class="shell">
    <div class="intro">
      <h1>Projects</h1>
    </div>
    <div class="cardgrid">
{cards}
    </div>
  </div>
</main>

"""
    html_out += footer("")
    open(os.path.join(OUT, "projects.html"), "w").write(html_out)


# ---------------------------------------------------------------- detail
def build_detail(key):
    p = P[key]
    root = "../"
    feats = "\n".join(
        f"          <li><strong>{t}.</strong> {d}</li>" for t, d in p["features"])
    info = "\n".join(
        f"            <div><dt>{k}</dt><dd>{v}</dd></div>" for k, v in p["info"])
    gal = "\n".join(
        f'''          <figure><img src="{root}assets/img/placeholder.svg" alt=""><figcaption>{c}</figcaption></figure>'''
        for c in p["gallery"])

    btns = []
    if p.get("github"):
        btns.append(f'<a class="btn btn--ghost" href="{p["github"]}">{I_GH}View source on GitHub</a>')
    if p.get("itch"):
        btns.append(f'<a class="btn btn--primary" href="{p["itch"]}">{I_PAD}Play on itch.io</a>')
    btn_html = ('<div class="actions">' + "".join(btns) + "</div>") if btns else ""

    html_out = head(f'{p["title"]} — {NAME}', p["desc_meta"], root)
    html_out += nav("projects", root)
    html_out += f"""
<main id="main" class="page">
  <div class="shell">

    <a class="backlink" href="{root}projects.html">Back to all projects</a>

    <section class="hero">
      <div class="hero__media"><img src="{root}assets/img/{p['img']}" alt="{p['title']} screenshot"></div>
      <div>
        <h1 class="hero__title">{p['title']}</h1>
        <p class="hero__desc">{p['long']}</p>
        <div class="hero__meta">
          {tags(p['tools'])}
          {btn_html}
        </div>
      </div>
    </section>

    <div class="detail">

      <section>
        <h2>Gallery</h2>
        <div class="gallery">
{gal}
        </div>
      </section>

      <section>
        <h2>What It Does</h2>
        {p['does']}
      </section>

      <section>
        <h2>Key Features</h2>
        <ul class="bullets">
{feats}
        </ul>
      </section>

      <section>
        <h2>How It Works</h2>
        {p['how']}
      </section>

      <section>
        <h2>Project Info</h2>
        <div class="panel">
          <dl class="info">
{info}
          </dl>
        </div>
      </section>

    </div>
  </div>
</main>

"""
    html_out += footer(root)
    open(os.path.join(OUT, "projects", p["page"]), "w").write(html_out)


if __name__ == "__main__":
    build_home()
    build_projects()
    for k in ["pi-server", "diamondsim", "raincheck", "snake"]:
        build_detail(k)
    print("built")
